### ISSUE TITLE
Bad Request: there is no administrators in the private chat

### ISSUE THREAD

**Issue by majid23** [MrRoundRobin/telegram.bot#260] opened 2016-11-20 13:32 UTC
Hi Robin,
Why i receive below exception.

Bad Request: there is no administrators in the private chat

**Comment by mhverbakel** [comment] 2016-11-20 13:42
Dear majid23,

This sounds like an issue with the Telegram platform itself, and not the library. Please contact https://telegram.me/BotSupport, they will probably be able to help you with your problem.

If the problem is not caused by the library, please close this issue, otherwise clarify how this problem comes from the library.

Kind regards,
Martijn Verbakel

**Closed** 2016-11-21 05:13 UTC
