### ISSUE TITLE
direct message

### ISSUE THREAD

**Issue by sinaprog** [MrRoundRobin/telegram.bot#253] opened 2016-11-12 12:05 UTC
Hi
Is there anyway to create chat with user in inline keyboard (user has not username)
like telegram.me/userid

**Comment by mhverbakel** [comment] 2016-11-20 13:53
Dear sinaprog,

Please close the issue (since it's not caused by the library) and contact https://telegram.me/BotSupport, they will probably be able to help you with your challenge.

Kind regards,
Martijn Verbakel

**Closed** 2016-11-20 14:28 UTC
