### ISSUE TITLE
Best practice for develop "Like and Dislike" buttons using Callback Queries

### ISSUE THREAD

**Issue by webiox** [MrRoundRobin/telegram.bot#259] opened 2016-11-19 09:09 UTC
Hi Robin.
I'm just wondering what is the best practice for develop a bot for getting like and dislike feedback from users?
It's important that this bot can manage a huge number of requests for avoiding Error code 429, Error: Too many requests.

**Comment by mhverbakel** [comment] 2016-11-20 13:45
Dear webiox,

Please close the issue (since it's not caused by the library) and contact https://telegram.me/BotSupport, they will probably be able to help you with your challenge.

Kind regards,
Martijn Verbakel

**Closed** 2016-11-20 14:30 UTC
