### ISSUE TITLE
ReplyKeyboardMarkup with RequestLocation Button Does not Reply any Messages

### ISSUE THREAD

**Issue by saswn** [MrRoundRobin/telegram.bot#252] opened 2016-11-07 14:08 UTC
### Steps to reproduce
Hey, there is a problem in your IOS Telegram Client
please read this note Carefully
# Problem:
i used this code in my C# Telegram BOT:

var keyboard = new ReplyKeyboardMarkup(new[]
{
new KeyboardButton("Share location please")
{
RequestLocation = true
}
});
long Chat_id = Bot.SendTextMessageAsync(message.Chat.Id, "Custom Text", replyMarkup: keyboard).Result.Chat.Id;

## What Code do ?
This code send a keyboard with Share Location Button to Client and when Client click on the button his location will share and location message have reply message id

## So what is problem ?
This Code Works Fine on Andriod and Desktop Version of Telegram but in IOS version when Client Click on Button that Location was sended is not reply
its just a Normal Location Message without Reply any other message
and its important for my Bot that receive a replied Location Message
Actually i just Receive a Location without this => "ReplyToMessage.MessageId;" Value in C#

Output in Andriod: (Works Fine)
![andriod](https://cloud.githubusercontent.com/assets/22630550/20060615/3d44b0e8-a511-11e6-9187-f1b4e047cd84.jpg)

Output in iOS: (Problem)
![ios](https://cloud.githubusercontent.com/assets/22630550/20060621/409a7fc0-a511-11e6-88a4-c8af52deecc9.jpg)
**in this picture you see Location is not replied Message but Client clicked on ReplyKeyboardMarkup Button**

### Expected  behavior
it must send a Location Message that Replied a Text Message

### Actual behavior
In Telegram IOS version ReplyKeyboardMarkup does not reply any thinks

*NuGet Package Version:* 10.4.0.0

*.NET Version:* 4.6

*IDE:* VS2013

*App:* iOS

**Comment by mhverbakel** [comment] 2016-11-07 14:48
Dear saswn,

This sounds like an issue with the Telegram platform itself, and not the library. Please contact https://telegram.me/BotSupport, they will probably be able to help you with your problem.

If the problem is not caused by the library, please close this issue, otherwise clarify how this problem comes from the library.

Kind regards,
Martijn Verbakel

**Closed** 2016-11-07 15:48 UTC

**Comment by a-a-k** [comment] 2016-11-08 04:17
@saswn, 
It can be solved by set for the Selective property false value.
Take a look [here](https://github.com/MrRoundRobin/telegram.bot/issues/251).
