### ISSUE TITLE
Support System Using Telegram

### ISSUE THREAD

**Issue by inornos** [MrRoundRobin/telegram.bot#255] opened 2016-11-16 13:34 UTC
We have a website which is used by registered users only, We are trying to develop support system use of telegram but we didn't find any solution to communicate to telegram end user(Not Telegram Bot)  and also we want pass unique current user id to telegram bot so we can track chat history also.

**Comment by mhverbakel** [comment] 2016-11-20 13:47
Dear inornos,

Please close the issue (since it's not caused by the library).

This kind of question is better fit for StackOverflow (although they encourage you to come up with your own solutions too).

Kind regards,
Martijn Verbakel

**Closed** 2016-11-20 14:29 UTC
